--Tornando um campo na tabela para ser not null
ALTER TABLE [TABELA DE PRODUTOs]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR(20) NOT NULL

--Adicionando um campo como primary key
ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])

--Deletando um dado da tabela em que um determinado campo é null
delete from [TABELA DE PRODUTOS] where [NOME DO CAMPO] is null

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR (5) NOT NULL

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA])

alter table [TABELA DE CLIENTE]
ALTER COLUMN[CPF]
CHAR(11) NOT NULL

alter table [TABELA DE CLIENTE]
ADD CONSTRAINT PK_TABELA_DE_CLIENTE
PRIMARY KEY CLUSTERED ([CPF])

INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [PRECO DE LISTA], [SABOR]) 
VALUES ('788976', 'Pedaços de Frutas - 1,5 Litros - Maça','PET', '1,5Litros', 18.011, 'Maça')