-- TRIIGER = Registrar determinados eventos que ocorre dentro do banco de dados
-- Deve ser utilizada com devido cautela, pois pode causar lentidão nos processamentos

-- FOR = Executa ao mesmo tempo que o comando
-- AFTER = Executa depois do comando
-- INSTEAD OF = Executa no lugar do comando

CREATE TABLE TB_FATURAMENTO(
	FT_DATAVENDA DATE NULL,
	FT_TOTAL FLOAT
)

CREATE TRIGGER tg_itens_vendidos
ON [ITENS VENDIDOS]
AFTER INSERT, UPDATE, DELETE
AS BEGIN
	DELETE FROM TB_FATURAMENTO

	INSERT INTO TB_FATURAMENTO(FT_DATAVENDA, FT_TOTAL)
		SELECT A.DATA AS DATA_VENDA, SUM(B.QUANTIDADE * B.[PREÇO]) AS TOTAL_VENDA
		FROM NOTAS A
		INNER JOIN [ITENS VENDIDOS] B
		ON A.NUMERO = B.NUMERO
		GROUP BY A.DATA;
END

INSERT INTO [NOTAS]([NUMERO], [DATA], [CPF], [MATRICULA], [IMPOSTO])VALUES('0100', '2018-05-15', '19223992743', '00236', 0.18)

INSERT INTO [ITENS VENDIDOS]([NUMERO], [CODIGO], [QUANTIDADE], [PREÇO])VALUES('0100', '1000889', 100, 16.80)
INSERT INTO [ITENS VENDIDOS]([NUMERO], [CODIGO], [QUANTIDADE], [PREÇO])VALUES('0100', '1002767', 200, 45.80)

SELECT * FROM TB_FATURAMENTO

CREATE TRIGGER tg_clientes_idade
ON [TABELA DE CLIENTES]
AFTER INSERT, UPDATE, DELETE
AS BEGIN
	UPDATE[TABELA DE CLIENTES]
	SET [IDADE] = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END