 --Alternando dados de uma determinada linha
 UPDATE [TABELA DE PRODUTOS]SET [EMBALAGEM] = 'Lata', [PRECO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE VENDEDORES] SET [PERCENTUAL COMISSAO] = 0.011
WHERE [MATRICULA] = 00235

UPDATE [TABELA DE VENDEDORES] SET [NOME] = 'Cláudia Morais Sousa'
WHERE [MATRICULA] = 00236
