
SELECT * FROM [VENDEDORES]

BEGIN TRANSACTION

UPDATE [VENDEDORES]
SET [COMISSAO] = [COMISSAO] * 1.15

INSERT INTO [VENDEDORES]([MATRICULA], [NOME], [BAIRRO], [COMISSAO], [DATA ADMISSAO], [FERIAS])
VALUES ('9999', 'João da Silva', 'Icaraí', 0.08, '2014-09-01', 0)

ROLLBACK

COMMIT