
CREATE TABLE TB_IDENTITY(
	ID INT IDENTITY (1,1) NOT NULL,
	DESCRITOR VARCHAR(20) NULL
)

INSERT INTO TB_IDENTITY(DESCRITOR)VALUES('CLIENTE X')

SELECT * FROM TB_IDENTITY

DROP TABLE TB_IDENTITY

CREATE TABLE TB_IDENTITY(
	ID INT IDENTITY (100,5) NOT NULL,
	DESCRITOR VARCHAR(20) NULL
)

INSERT INTO TB_IDENTITY(DESCRITOR)VALUES('CLIENTE X')
INSERT INTO TB_IDENTITY(DESCRITOR)VALUES('CLIENTE Y')

SELECT * FROM TB_IDENTITY