--Deleta determinada linha do banco de dados
DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = 1078680

--Deleta a tabela toda
DELETE FROM [NOME DA TABELA]

DELETE FROM [TABELA DE VENDEDORES]
WHERE MATRICULA = 00235