-- Relacionamento de entidade notas com cliente através de chave estrangeira
ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTES]
FOREIGN KEY ([CPF]) REFERENCES [TABELA DE CLIENTES] ([CPF])

-- Tabela com chave primária composta
CREATE TABLE [ITENS VENDIDOS](
    [NUMERO] VARCHAR(5) NOT NULL,
    [CODIGO] VARCHAR(10) NOT NULL,
    [QUANTIDADE] INT NULL,
    [PREÇO] FLOAT NULL, 
CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED ([NUMERO] ASC, [CODIGO] ASC) 
WITH (
    PAD_INDEX = OFF, 
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = OFF, 
    ALLOW_ROW_LOCKS = ON, 
    ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]) ON [PRIMARY]

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  
CONSTRAINT [FK_ITENS VENDIDOS_NOTAS] FOREIGN KEY([NUMERO])
REFERENCES [dbo].[NOTAS] ([NUMERO])

ALTER TABLE [dbo].[ITENS VENDIDOS] 
CHECK CONSTRAINT [FK_ITENS VENDIDOS_NOTAS]

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  
CONSTRAINT [FK_ITENS VENDIDOS_TABELA DE PRODUTOS] FOREIGN KEY([CODIGO])
REFERENCES [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO])

ALTER TABLE [dbo].[ITENS VENDIDOS] 
CHECK CONSTRAINT [FK_ITENS VENDIDOS_TABELA DE PRODUTOS]
